return {
  "williamboman/mason.nvim",
  opts = {
    ensure_installed = {
      "actionlint",
      "bash-language-server",
      "biome",
      "css-lsp",
      "debugpy",
      "deno",
      "dockerfile-language-server",
      "flake8",
      "gitui",
      "hadolint",
      "html-lsp",
      "intelephense",
      "json-lsp",
      "lemminx",
      "lua-language-server",
      "markdownlint",
      "prettier",
      "pyright",
      "ruff-lsp",
      "rust-analyzer",
      "shellcheck",
      "shfmt",
      "sqlfmt",
      "sqlls",
      "stylua",
      "svelte-language-server",
      "tailwindcss-language-server",
      "taplo",
      "typescript-language-server",
      "vim-language-server",
      "yaml-language-server",
    },
  },
}
