return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = {
      "bash",
      "css",
      "diff",
      "dockerfile",
      "gitignore",
      "go",
      "html",
      "http",
      "ini",
      "javascript",
      "jq",
      "json",
      "json5",
      "lua",
      "markdown",
      "markdown_inline",
      "query",
      "regex",
      "rust",
      "tsx",
      "typescript",
      "vim",
      "yaml",
    },
  },
}
