return {
	["gD"] = "<Cmd>lua vim.lsp.buf.declaration()<CR>",
	["gd"] = "<Cmd>lua vim.lsp.buf.definition()<CR>",
	["K"] = "<Cmd>lua vim.lsp.buf.hover()<CR>",
	["gi"] = "<cmd>lua vim.lsp.buf.implementation()<CR>",
	["<C-k>"] = "<cmd>lua vim.lsp.buf.signature_help()<CR>",
	["<space>wa"] = "<cmd>lua vim.lsp.buf.add_workspace_folder()<CR>",
	["<space>wr"] = "<cmd>lua vim.lsp.buf.remove_workspace_folder()<CR>",
	["<space>wl"] = "<cmd>lua print(vim.inspect(vim.lsp.buf.list_workspace_folders()))<CR>",
	["<space>D"] = "<cmd>lua vim.lsp.buf.type_definition()<CR>",
	["<space>rn"] = "<cmd>lua vim.lsp.buf.rename()<CR>",
	["<space>ca"] = "<cmd>lua vim.lsp.buf.code_action()<CR>",
	["gr"] = "<cmd>lua vim.lsp.buf.references()<CR>",
	["<space>e"] = "<cmd>lua vim.lsp.diagnostic.show_line_diagnostics()<CR>",
	["[d"] = "<cmd>lua vim.lsp.diagnostic.goto_prev()<CR>",
	["]d"] = "<cmd>lua vim.lsp.diagnostic.goto_next()<CR>",
	["<space>q"] = "<cmd>lua vim.lsp.diagnostic.set_loclist()<CR>",
	["<leader>f"] = "<cmd>lua vim.lsp.buf.formatting()<CR>",
}
